image: gradle:latest

stages:
  - build
  - publish

build:
  stage: build
  script: gradle clean build
  artifacts:
    paths:
      - build/libs/telegroo*.jar
  only:
    - master

publish:
  stage: publish
  script:
    - gradle publish
    - git clone https://gitlab.com/teslex/repo
    - cp -r build/repo/* repo
    - cd repo
    - git config --global user.name 'teslex bot'
    - git config --global user.email 'teslex.bot@gmail.com'
    - git add .
    - git commit -m 'Update telegroo'
    - git push https://david.kohut:${GITLAB_PRIVATE_KEY}@gitlab.com/teslex/repo
