image: openjdk:12

stages:
  - publish

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apk update && apk add git

# test:
#   stage: test
#   script:
#     - mkdir -p telegroo/src/test/resources/
#     - echo "token=${TEST_BOT_TOKEN}" >> telegroo/src/test/resources/test.properties
#     - gradle test


publish-teslex:
  stage: publish
  script:
    - bash deploy/publish-teslex.sh
  only:
    - v1


publish-teslex-snapshot:
  stage: publish
  script:
    - git clone https://gitlab.com/teslex/repo
    - bash deploy/publish-teslex-snapshot.sh
  only:
    - master


#bintray-upload:
#  stage: publish
#  script:
#    - bash deploy/publish-bintray.sh
#  only:
#    - bintray
