image: gradle:latest

stages:
  - build
  - publish

build:
  stage: build
  script: gradle clean build
  artifacts:
    paths:
      - build/libs/telegroo*.jar
  only:
    - master

publish:
  stage: publish
  script:
    - gradle clean publish
    - git clone https://gitlab.com/teslex/repo
    - cp -r telegroo/build/repo/* repo
    - cp -r api/build/repo/* repo
    - cd repo
    - git config --global user.name 'TesLex Bot'
    - git config --global user.email 'teslex.bot@gmail.com'
    - git add .
    - git commit -m 'Update telegroo'
    - git push https://teslex.bot:${GITLAB_PRIVATE_KEY}@gitlab.com/teslex/repo
  only:
    - master

publish-snapshot:
  stage: publish
  script:
    - gradle clean publish
    - git clone https://gitlab.com/teslex/repo
    - cp -r telegroo/build/repo/* repo
    - cp -r api/build/repo/* repo
    - cd repo
    - git config --global user.name 'TesLex Bot'
    - git config --global user.email 'teslex.bot@gmail.com'
    - git add .
    - git commit -m 'Update telegroo'
    - git push https://teslex.bot:${GITLAB_PRIVATE_KEY}@gitlab.com/teslex/repo
  except:
    - master