image: gradle:latest

stages:
  # - test
  - build
  - publish


# test:
#   stage: test
#   script:
#     - mkdir -p telegroo/src/test/resources/
#     - echo "token=${TEST_BOT_TOKEN}" >> telegroo/src/test/resources/test.properties
#     - gradle test


publish-teslex:
  stage: publish
  script:
    - "[ $(gradle properties -q | grep 'isSnapshot:' | awk '{print $2}') == 'true' ] && exit 1"
    - gradle clean publish
    - git clone https://gitlab.com/teslex/repo
    - cp -r telegram-api/build/repo/* repo
    - cp -r telegroo-api/build/repo/* repo
    - cp -r telegroo-dsl/build/repo/* repo
    - cp -r telegroo/build/repo/* repo
    - cd repo
    - git config --global user.name 'TesLex Bot'
    - git config --global user.email 'teslex.bot@gmail.com'
    - git add .
    - git commit -m 'Update telegroo'
    - git push https://teslex.bot:${GITLAB_PRIVATE_KEY}@gitlab.com/teslex/repo
  only:
    - master


publish-teslex-snapshot:
  stage: publish
  script:
    - "[ $(gradle properties -q | grep 'isSnapshot:' | awk '{print $2}') != 'true' ] && exit 1"
    - HERE=$(pwd)
    - gradle clean publish
    - git clone https://gitlab.com/teslex/repo
    - cd $HERE/repo/snapshots/tech/teslex/telegroo/telegroo && find . -type d -not -name "$(find . -type d -printf '%P\n' | sort -r | head -n 1)" -not -name "$(find . -type d -printf '%P\n' | sort -r | head -n 2 | sort | head -n 1)" -printf '%P\n' | xargs rm -rf
    - cd $HERE/repo/snapshots/tech/teslex/telegroo/telegroo-api && find . -type d -not -name "$(find . -type d -printf '%P\n' | sort -r | head -n 1)" -not -name "$(find . -type d -printf '%P\n' | sort -r | head -n 2 | sort | head -n 1)" -printf '%P\n' | xargs rm -rf
    - cd $HERE/repo/snapshots/tech/teslex/telegroo/telegram-api && find . -type d -not -name "$(find . -type d -printf '%P\n' | sort -r | head -n 1)" -not -name "$(find . -type d -printf '%P\n' | sort -r | head -n 2 | sort | head -n 1)" -printf '%P\n' | xargs rm -rf
    - cd $HERE/repo/snapshots/tech/teslex/telegroo/telegroo-dsl && find . -type d -not -name "$(find . -type d -printf '%P\n' | sort -r | head -n 1)" -not -name "$(find . -type d -printf '%P\n' | sort -r | head -n 2 | sort | head -n 1)" -printf '%P\n' | xargs rm -rf
    - cp -r $HERE/telegram-api/build/repo/* repo
    - cp -r $HERE/telegroo-api/build/repo/* repo
    - cp -r $HERE/telegroo-dsl/build/repo/* repo
    - cp -r $HERE/telegroo/build/repo/* repo
    - cd $HERE/repo
    - git config --global user.name 'TesLex Bot'
    - git config --global user.email 'teslex.bot@gmail.com'
    - git add .
    - git commit -m 'Update telegroo'
    - git push https://teslex.bot:${GITLAB_PRIVATE_KEY}@gitlab.com/teslex/repo
  only:
    - '1.0'


bintray-upload:
  stage: publish
  script:
    - "[ $(gradle properties -q | grep 'isSnapshot:' | awk '{print $2}') == 'true' ] && exit 1"
    - gradle test
    - gradle bintrayUpload
  only:
    - master
